source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Shufflers_Example', :exclusive => true do
  pod "Shufflers", :path => "../"
end

target 'Shufflers_Tests', :exclusive => true do
  pod "Shufflers", :path => "../"

  
end
